import { TaskItem, TaskStatus, TaskPriority } from "../types/tasks";

export const mockTasks: TaskItem[] = [
  {
    id: "1",
    text: "High priority task",
    markdown: "- [ ] ❗ High priority task",
    content: "- [ ] ❗ High priority task",
    fcontent: "❗ High priority task",
    box: "box1",
    boxName: "Notebook 1",
    root_id: "doc1",
    path: "/path1",
    created: "2024-01-01T00:00:00Z",
    updated: "2024-01-01T00:00:00Z",
    type: "i",
    subtype: "t",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
  },
  {
    id: "2",
    text: "Completed task",
    markdown: "- [x] Completed task",
    content: "- [x] Completed task",
    fcontent: "Completed task",
    box: "box1",
    boxName: "Notebook 1",
    root_id: "doc1",
    path: "/path1",
    created: "2024-01-02T00:00:00Z",
    updated: "2024-01-02T00:00:00Z",
    type: "i",
    subtype: "t",
    status: TaskStatus.DONE,
    priority: TaskPriority.NORMAL,
  },
  {
    id: "3",
    text: "Urgent task",
    markdown: "- [ ] ‼️ Urgent task",
    content: "- [ ] ‼️ Urgent task",
    fcontent: "‼️ Urgent task",
    box: "box1",
    boxName: "Notebook 1",
    root_id: "doc1",
    path: "/path1",
    created: "2024-01-03T00:00:00Z",
    updated: "2024-01-03T00:00:00Z",
    type: "i",
    subtype: "t",
    status: TaskStatus.TODO,
    priority: TaskPriority.URGENT,
  },
];

export const mockTaskWithSubBlocks: TaskItem = {
  id: "4",
  text: "Task with sub-blocks",
  markdown: "- [ ] Task with sub-blocks",
  content: "- [ ] Task with sub-blocks",
  fcontent: "Task with sub-blocks",
  box: "box1",
  boxName: "Notebook 1",
  root_id: "doc1",
  path: "/path1",
  created: "2024-01-04T00:00:00Z",
  updated: "2024-01-04T00:00:00Z",
  type: "i",
  subtype: "t",
  status: TaskStatus.TODO,
  priority: TaskPriority.NORMAL,
};
